# Generated by Django 3.2.6 on 2021-08-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='sex',
            field=models.CharField(choices=[('M', 'Мужчина'), ('W', 'Женщина')], max_length=50, verbose_name='Пол'),
        ),
    ]
