# Generated by Django 3.2.6 on 2021-08-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.CharField(default='00:00:00', max_length=10, verbose_name='Локальное время отправки'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки сообщения'),
        ),
    ]
