# Generated by Django 3.2.6 on 2021-08-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_user_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='joined_at',
        ),
    ]
