# Generated by Django 3.2.6 on 2021-08-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210817_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='avatar',
            field=models.ImageField(default='static/chat/images/default.jpg', upload_to='static/chat/images/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='sex',
            field=models.CharField(choices=[('M', 'Мужчина'), ('W', 'Женщина')], default='Неопределенный', max_length=50, verbose_name='Пол'),
        ),
    ]
