# Generated by Django 3.2.6 on 2021-08-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210817_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='sex',
            field=models.CharField(choices=[('M', 'Мужчина'), ('W', 'Женщина'), ('N', 'Неопределенный')], default='N', max_length=50, verbose_name='Пол'),
        ),
    ]
